[theme]
# Modern primary accent (vibrant but not overwhelming)
primaryColor = '#6C5CE7'  # Sophisticated purple

# Dark background for main content (better contrast)
backgroundColor = '#1E293B'  # Cool dark blue-gray

# Clean secondary background (light but not harsh)
secondaryBackgroundColor = '#F8F9FA'  # Very light gray

# Text colors (now dynamic for better contrast)
textColor = '#FFFFFF'  # White for dark backgrounds
secondaryTextColor = '#1E293B'  # Dark text for light backgrounds (input boxes)
font = "sans serif"

# Additional modern touches
base = "dark"  # Dark mode by default
widgetBackgroundColor = '#2D3748'  # Slightly lighter than bg
widgetBorderColor = '#4A5568'  # Subtle border